### ISSUE TITLE
Missing json data 

### ISSUE THREAD

**Issue by shubhamagarwal92** [kylemcdonald/nvidia-co2#3]
Hi @kylemcdonald, 

Cool repo. However, I think you missed `package_data` in `setup.py`

``` 
Traceback (most recent call last):
  File "/home/shubham/anaconda3/envs/visdialch/bin/nvidia-co2", line 10, in <module>
    sys.exit(main())
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 124, in main
    nvidia_co2(args.mode)
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 100, in nvidia_co2
    msg = convert_watts(watts, mode)
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 93, in convert_watts
    gco2eqph = watts_to_gco2eqph(watts)
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 60, in watts_to_gco2eqph
    gco2eqpkwh = get_carbon_intensity()
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 56, in get_carbon_intensity
    carbon_intensity = get_carbon_intensity_by_ip(ip)
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 36, in new_func
    d[param] = func(param)
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/__main__.py", line 49, in get_carbon_intensity_by_ip
    from .metrics import get_zone_information_by_coords
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/metrics.py", line 4, in <module>
    from .constants import REGIONS_WITH_BOUNDING_BOXES, ZONE_INFO, ZONE_NAMES
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/constants.py", line 71, in <module>
    REGIONS_WITH_BOUNDING_BOXES = load_regions_with_bounding_boxes()
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/constants.py", line 63, in load_regions_with_bounding_boxes
    dir_path, 'data/zonegeometries.json'))
  File "/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/constants.py", line 19, in read_terrible_json
    with open(path, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shubham/anaconda3/envs/visdialch/lib/python3.6/site-packages/nvidia_co2/data/zonegeometries.json'
```

**Comment by kylemcdonald** [comment]
Closed by #4
